[package]
name = "fluent-migrator"
version = "1.0.0"
edition = "2018"
authors = ["Greg Tatum"]
description = "Migrate Firefox .dtd and .properties files to Fluent."

[features]

[dependencies]
clap = "2.33"
nom = { version = "6.2", features = ["alloc"] }
convert_case = "0.4"
nom-trace = "0.2"
