# Replace this with your path to mozilla central
GECKO=~/dev/gecko

# Property files
fluent-migrator --save --overwrite \
  $GECKO/intl/locale/encodingsgroups.properties \
  $GECKO/intl/locale/language.properties \
  $GECKO/security/manager/locales/en-US/chrome/pippki/pippki.properties \
  $GECKO/security/manager/locales/en-US/chrome/pipnss/pipnss.properties \
  $GECKO/security/manager/locales/en-US/chrome/pipnss/nsserrors.properties \
  $GECKO/layout/mathml/mathfont.properties \
  $GECKO/layout/mathml/mathfontUnicode.properties \
  $GECKO/layout/mathml/mathfontSTIXGeneral.properties \
  $GECKO/netwerk/locales/en-US/necko.properties \
  $GECKO/browser/locales/en-US/pdfviewer/viewer.properties \
  $GECKO/browser/locales/en-US/pdfviewer/chrome.properties \
  $GECKO/browser/locales/en-US/chrome/overrides/appstrings.properties \
  $GECKO/browser/locales/en-US/chrome/browser/sitePermissions.properties \
  $GECKO/browser/locales/en-US/chrome/browser/taskbar.properties \
  $GECKO/browser/locales/en-US/chrome/browser/accounts.properties \
  $GECKO/browser/locales/en-US/chrome/browser/customizableui/customizableWidgets.properties \
  $GECKO/browser/locales/en-US/chrome/browser/siteData.properties \
  $GECKO/browser/locales/en-US/chrome/browser/browser.properties \
  $GECKO/browser/locales/en-US/chrome/browser/app-extension-fields.properties \
  $GECKO/browser/locales/en-US/chrome/browser/places/bookmarkProperties.properties \
  $GECKO/browser/locales/en-US/chrome/browser/places/places.properties \
  $GECKO/browser/locales/en-US/chrome/browser/syncSetup.properties \
  $GECKO/browser/locales/en-US/chrome/browser/webrtcIndicator.properties \
  $GECKO/browser/locales/en-US/chrome/browser/tabbrowser.properties \
  $GECKO/browser/locales/en-US/chrome/browser/feeds/subscribe.properties \
  $GECKO/browser/locales/en-US/chrome/browser/uiDensity.properties \
  $GECKO/browser/locales/en-US/chrome/browser/safebrowsing/safebrowsing.properties \
  $GECKO/browser/locales/en-US/chrome/browser/translation.properties \
  $GECKO/browser/locales/en-US/chrome/browser/shellservice.properties \
  $GECKO/browser/locales/en-US/chrome/browser/downloads/downloads.properties \
  $GECKO/browser/locales/en-US/chrome/browser/search.properties \
  $GECKO/browser/locales/en-US/chrome/browser-region/region.properties \
  $GECKO/browser/locales/en-US/installer/override.properties \
  $GECKO/browser/locales/en-US/installer/mui.properties \
  $GECKO/browser/locales/en-US/installer/nsisstrings.properties \
  $GECKO/browser/locales/en-US/installer/custom.properties \
  $GECKO/browser/extensions/formautofill/locales/en-US/formautofill.properties \
  $GECKO/browser/extensions/report-site-issue/locales/en-US/webcompat.properties \
  $GECKO/devtools/shared/locales/en-US/highlighters.properties \
  $GECKO/devtools/shared/locales/en-US/screenshot.properties \
  $GECKO/devtools/shared/locales/en-US/shared.properties \
  $GECKO/devtools/shared/locales/en-US/styleinspector.properties \
  $GECKO/devtools/shared/locales/en-US/eyedropper.properties \
  $GECKO/devtools/shared/locales/en-US/debugger.properties \
  $GECKO/devtools/startup/locales/en-US/key-shortcuts.properties \
  $GECKO/devtools/startup/locales/en-US/startup.properties \
  $GECKO/devtools/client/locales/en-US/markers.properties \
  $GECKO/devtools/client/locales/en-US/graphs.properties \
  $GECKO/devtools/client/locales/en-US/dom.properties \
  $GECKO/devtools/client/locales/en-US/performance.properties \
  $GECKO/devtools/client/locales/en-US/har.properties \
  $GECKO/devtools/client/locales/en-US/toolbox.properties \
  $GECKO/devtools/client/locales/en-US/boxmodel.properties \
  $GECKO/devtools/client/locales/en-US/menus.properties \
  $GECKO/devtools/client/locales/en-US/device.properties \
  $GECKO/devtools/client/locales/en-US/accessibility.properties \
  $GECKO/devtools/client/locales/en-US/animationinspector.properties \
  $GECKO/devtools/client/locales/en-US/inspector.properties \
  $GECKO/devtools/client/locales/en-US/jsonview.properties \
  $GECKO/devtools/client/locales/en-US/changes.properties \
  $GECKO/devtools/client/locales/en-US/shared.properties \
  $GECKO/devtools/client/locales/en-US/network-throttling.properties \
  $GECKO/devtools/client/locales/en-US/sourceeditor.properties \
  $GECKO/devtools/client/locales/en-US/responsive.properties \
  $GECKO/devtools/client/locales/en-US/netmonitor.properties \
  $GECKO/devtools/client/locales/en-US/memory.properties \
  $GECKO/devtools/client/locales/en-US/font-inspector.properties \
  $GECKO/devtools/client/locales/en-US/filterwidget.properties \
  $GECKO/devtools/client/locales/en-US/startup.properties \
  $GECKO/devtools/client/locales/en-US/layout.properties \
  $GECKO/devtools/client/locales/en-US/debugger.properties \
  $GECKO/devtools/client/locales/en-US/webconsole.properties \
  $GECKO/devtools/client/locales/en-US/components.properties \
  $GECKO/devtools/client/locales/en-US/jit-optimizations.properties \
  $GECKO/mobile/locales/en-US/overrides/appstrings.properties \
  $GECKO/mobile/locales/en-US/chrome/region.properties \
  $GECKO/mobile/android/locales/en-US/chrome/passwordmgr.properties \
  $GECKO/mobile/android/locales/en-US/chrome/browser.properties \
  $GECKO/mobile/android/locales/en-US/chrome/config.properties \
  $GECKO/nsprpub/pr/src/misc/prerr.properties \
  $GECKO/dom/locales/en-US/chrome/svg/svg.properties \
  $GECKO/dom/locales/en-US/chrome/mathml/mathml.properties \
  $GECKO/dom/locales/en-US/chrome/appstrings.properties \
  $GECKO/dom/locales/en-US/chrome/security/caps.properties \
  $GECKO/dom/locales/en-US/chrome/security/csp.properties \
  $GECKO/dom/locales/en-US/chrome/security/security.properties \
  $GECKO/dom/locales/en-US/chrome/layout/htmlparser.properties \
  $GECKO/dom/locales/en-US/chrome/layout/css.properties \
  $GECKO/dom/locales/en-US/chrome/layout/layout_errors.properties \
  $GECKO/dom/locales/en-US/chrome/layout/xul.properties \
  $GECKO/dom/locales/en-US/chrome/layout/xmlparser.properties \
  $GECKO/dom/locales/en-US/chrome/layout/MediaDocument.properties \
  $GECKO/dom/locales/en-US/chrome/layout/printing.properties \
  $GECKO/dom/locales/en-US/chrome/layout/HtmlForm.properties \
  $GECKO/dom/locales/en-US/chrome/global-strres.properties \
  $GECKO/dom/locales/en-US/chrome/dom/dom.properties \
  $GECKO/dom/locales/en-US/chrome/plugins.properties \
  $GECKO/dom/locales/en-US/chrome/xslt/xslt.properties \
  $GECKO/dom/locales/en-US/chrome/nsWebBrowserPersist.properties \
  $GECKO/dom/locales/en-US/chrome/accessibility/AccessFu.properties \
  $GECKO/dom/locales/en-US/chrome/accessibility/win/accessible.properties \
  $GECKO/dom/locales/en-US/chrome/accessibility/mac/accessible.properties \
  $GECKO/dom/locales/en-US/chrome/accessibility/unix/accessible.properties \
  $GECKO/toolkit/locales/en-US/chrome/passwordmgr/passwordmgr.properties \
  $GECKO/toolkit/locales/en-US/chrome/places/places.properties \
  $GECKO/toolkit/locales/en-US/chrome/autoconfig/autoconfig.properties \
  $GECKO/toolkit/locales/en-US/chrome/alerts/alert.properties \
  $GECKO/toolkit/locales/en-US/chrome/global-platform/win/platformKeys.properties \
  $GECKO/toolkit/locales/en-US/chrome/global-platform/win/intl.properties \
  $GECKO/toolkit/locales/en-US/chrome/global-platform/mac/platformKeys.properties \
  $GECKO/toolkit/locales/en-US/chrome/global-platform/mac/intl.properties \
  $GECKO/toolkit/locales/en-US/chrome/global-platform/unix/platformKeys.properties \
  $GECKO/toolkit/locales/en-US/chrome/global-platform/unix/intl.properties \
  $GECKO/toolkit/locales/en-US/chrome/global/commonDialogs.properties \
  $GECKO/toolkit/locales/en-US/chrome/global/keys.properties \
  $GECKO/toolkit/locales/en-US/chrome/global/dialog.properties \
  $GECKO/toolkit/locales/en-US/chrome/global/fallbackMenubar.properties \
  $GECKO/toolkit/locales/en-US/chrome/global/wizard.properties \
  $GECKO/toolkit/locales/en-US/chrome/global/browser.properties \
  $GECKO/toolkit/locales/en-US/chrome/global/global-extension-fields.properties \
  $GECKO/toolkit/locales/en-US/chrome/global/resetProfile.properties \
  $GECKO/toolkit/locales/en-US/chrome/global/filepicker.properties \
  $GECKO/toolkit/locales/en-US/chrome/global/viewSource.properties \
  $GECKO/toolkit/locales/en-US/chrome/global/printdialog.properties \
  $GECKO/toolkit/locales/en-US/chrome/global/contentAreaCommands.properties \
  $GECKO/toolkit/locales/en-US/chrome/global/intl.properties \
  $GECKO/toolkit/locales/en-US/chrome/global/aboutStudies.properties \
  $GECKO/toolkit/locales/en-US/chrome/global/narrate.properties \
  $GECKO/toolkit/locales/en-US/chrome/global/findbar.properties \
  $GECKO/toolkit/locales/en-US/chrome/global/extensions.properties \
  $GECKO/toolkit/locales/en-US/chrome/global/aboutReader.properties \
  $GECKO/toolkit/locales/en-US/chrome/global/autocomplete.properties \
  $GECKO/toolkit/locales/en-US/chrome/mozapps/update/updates.properties \
  $GECKO/toolkit/locales/en-US/chrome/mozapps/extensions/extensions.properties \
  $GECKO/toolkit/locales/en-US/chrome/mozapps/profile/profileSelection.properties \
  $GECKO/toolkit/locales/en-US/chrome/mozapps/downloads/downloads.properties \
  $GECKO/toolkit/locales/en-US/chrome/mozapps/downloads/unknownContentType.properties \
  $GECKO/toolkit/content/filepicker.properties \
  $GECKO/services/sync/locales/en-US/sync.properties \
  $GECKO/remote/marionette/chrome/test_dialog.properties
